source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HWAYCoreData_Example', :exclusive => true do
  pod "HWAYCoreData", :path => "../"
end

target 'HWAYCoreData_Tests', :exclusive => true do
  pod "HWAYCoreData", :path => "../"

  
end
